### ISSUE TITLE
【一般】用户门户》资源管理》资源使用情况，查看应用资源占用详细情况时，报错。

### ISSUE THREAD

**Issue by yuanhj3** [AIPaaS/PaaS-FE-Platform-Portal#12]
用户门户》资源管理》资源使用情况，查看应用资源占用详细情况时，报错。
信息如下：
11:05:59,160 ERROR BinarySpringServlet:273 -  mvc process error! 
  com.binary.framework.exception.DubboException:  call remote service 'PcAppSvc.queryAppNetZoneResInfo()' error! Unknown column 'IMAGE' in 'field list'
                at com.binary.framework.dubbo.rest.DubboRestClient.request(DubboRestClient.java:97)
                at com.binary.framework.dubbo.rest.impl.DubboRestClientHandler.doRemoteMethod(DubboRestClientHandler.java:74)
                at com.binary.framework.dubbo.rest.impl.DubboRestClientHandler.invoke(DubboRestClientHandler.java:46)
                at com.sun.proxy.$Proxy28.queryAppNetZoneResInfo(Unknown Source)
                at com.aic.paas.web.dep.peer.impl.PcAppPeerImpl.queryAppNetZoneResInfo(PcAppPeerImpl.java:242)
                at com.aic.paas.web.dep.mvc.PcAppMvc.queryAppNetZoneResInfo(PcAppMvc.java:87)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:606)
                at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176)
                at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:436)
                at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:424)
                at com.binary.framework.spring.BinarySpringServlet.doDispatch(BinarySpringServlet.java:222)
                at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
                at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
                at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:789)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
                at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
                at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221)
                at com.binary.framework.web.filter.LoginValidateFilter.doFilter(LoginValidateFilter.java:216)
                at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
                at com.binary.framework.web.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:28)
                at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
                at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
                at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
                at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
                at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)

**Comment by yuanman001** [comment]
本地调试未重现此问题，可查看资源占用详情，需重现后定位问题。

**Comment by yuanhj3** [comment]
修改数据库表字段后，已无此问题
