### ISSUE TITLE
【一般】用户门户》部署管理》应用部署配置，开放服务步骤，输入数据保存报错。

### ISSUE THREAD

**Issue by yuanhj3** [AIPaaS/PaaS-FE-Platform-Portal#28]
用户门户》部署管理》应用部署配置，开放服务步骤，输入数据保存报错。
报错信息如下：
        at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
16:38:44,238 ERROR BinarySpringServlet:273 -  mvc process error! 
  com.binary.framework.exception.DubboException:  call remote service 'PcAppImageSvc.saveAppImageOpenService()' error!  is exists code 'yhj-yingyong2-yingyong2rongyi1'! 
                at com.binary.framework.dubbo.rest.DubboRestClient.request(DubboRestClient.java:141)
                at com.binary.framework.dubbo.rest.impl.DubboRestClientHandler.doRemoteMethod(DubboRestClientHandler.java:74)
                at com.binary.framework.dubbo.rest.impl.DubboRestClientHandler.invoke(DubboRestClientHandler.java:46)
                at com.sun.proxy.$Proxy26.saveAppImageOpenService(Unknown Source)
                at com.aic.paas.web.dep.peer.impl.PcAppImagePeerImpl.saveAppImageOpenService(PcAppImagePeerImpl.java:274)
                at com.aic.paas.web.dep.mvc.PcAppImageMvc.saveAppImageOpenService(PcAppImageMvc.java:170)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:606)
                at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176)
                at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:436)
                at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:424)
                at com.binary.framework.spring.BinarySpringServlet.doDispatch(BinarySpringServlet.java:222)
                at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
                at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
                at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:789)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
                at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
                at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221)
                at com.binary.framework.web.filter.LoginValidateFilter.doFilter(LoginValidateFilter.java:216)
                at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
                at com.binary.framework.web.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:28)
                at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
                at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
                at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
                at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
                at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
                at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)
                at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
                at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
                at org.mortbay.jetty.Server.handle(Server.java:326)
                at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
                at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945)
                at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
                at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
                at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
                at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
                at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
        at com.binary.framework.dubbo.rest.DubboRestClient.request(DubboRestClient.java:141)
        at com.binary.framework.dubbo.rest.impl.DubboRestClientHandler.doRemoteMethod(DubboRestClientHandler.java:74)
        at com.binary.framework.dubbo.rest.impl.DubboRestClientHandler.invoke(DubboRestClientHandler.java:46)
        at com.sun.proxy.$Proxy26.saveAppImageOpenService(Unknown Source)
        at com.aic.paas.web.dep.peer.impl.PcAppImagePeerImpl.saveAppImageOpenService(PcAppImagePeerImpl.java:274)
        at com.aic.paas.web.dep.mvc.PcAppImageMvc.saveAppImageOpenService(PcAppImageMvc.java:170)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176)
        at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:436)
        at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:424)
        at com.binary.framework.spring.BinarySpringServlet.doDispatch(BinarySpringServlet.java:222)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:789)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)

**Comment by liwenxian** [comment]
已修复

**Comment by yuanhj3** [comment]
已解决
