### ISSUE TITLE
用户门户》部署管理》外部服务管理，添加外部服务提交时，consul注册不成功，后台报错。

### ISSUE THREAD

**Issue by yuanhj3** [AIPaaS/PaaS-FE-Platform-Portal#37]
用户门户》部署管理》外部服务管理，添加外部服务提交时，consul注册不成功，后台报错。
信息如下：
2016-03-18 at 10:03:59 CST DEBUG org.jboss.resteasy.logging.impl.Log4jLogger 60 debug - PathInfo: /cpaas/external/manage/add
2016-03-18 at 10:03:59 CST DEBUG org.springframework.transaction.support.AbstractPlatformTransactionManager 367 getTransaction - Creating new transaction with name [com.ai.paas.cpaas.be.am.service.impl.ResClusterInfoServiceImpl.getClusterInfo]: PROPAGATION_REQUIRED,ISOLATION_DEFAULT; '',-java.lang.Exception
2016-03-18 at 10:03:59 CST DEBUG org.apache.commons.dbcp2.PoolableConnectionFactory 346 validateObject - Failed to validate a poolable connection. java.sql.SQLException: isValid() returned false
        at org.apache.commons.dbcp2.PoolableConnection.validate(PoolableConnection.java:284) ~[commons-dbcp2-2.1.jar:2.1]
        at org.apache.commons.dbcp2.PoolableConnectionFactory.validateConnection(PoolableConnectionFactory.java:357) ~[commons-dbcp2-2.1.jar:2.1]
        at org.apache.commons.dbcp2.PoolableConnectionFactory.validateObject(PoolableConnectionFactory.java:342) [commons-dbcp2-2.1.jar:2.1]
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:492) [commons-pool2-2.3.jar:2.3]
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363) [commons-pool2-2.3.jar:2.3]
        at org.apache.commons.dbcp2.PoolingDataSource.getConnection(PoolingDataSource.java:134) [commons-dbcp2-2.1.jar:2.1]
        at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1533) [commons-dbcp2-2.1.jar:2.1]
        at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:204) [spring-jdbc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373) [spring-tx-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:463) [spring-tx-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:276) [spring-tx-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) [spring-tx-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653) [spring-aop-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at com.ai.paas.cpaas.be.am.service.impl.ResClusterInfoServiceImpl$$EnhancerBySpringCGLIB$$38f1c898.getClusterInfo(<generated>) [spring-core-4.1.6.RELEASE.jar:?]
        at com.ai.paas.cpaas.be.srv.manage.impl.ExternalServiceManage.register(ExternalServiceManage.java:45) [PaaS-BE-AM-0.1-SNAPSHOT.jar:?]
        at com.ai.paas.cpaas.be.srv.manage.impl.ExternalServiceManage.add(ExternalServiceManage.java:33) [PaaS-BE-AM-0.1-SNAPSHOT.jar:?]
        at com.alibaba.dubbo.common.bytecode.Wrapper1.invokeMethod(Wrapper1.java) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:46) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:64) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:60) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:132) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.common.bytecode.proxy0.add(proxy0.java) [dubbox-2.8.3.jar:2.8.3]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_55]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_55]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_55]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_55]

**Comment by yuanhj3** [comment]
注册成功了，但 be-am还是报上面的异常，后续会持续跟踪
